export const MENU_DATA = [
  {
    id: 1,
    menu: '전주비빔밥',
    price: 8500,
    image: require('../assets/foodImage/food_img_1.png'),
    selectImage: require('../assets/foodImage/food_s_img_1.png'),
    foodImage: require('../assets/foodImage/food_1.png'),
  },
  {
    id: 2,
    menu: '육회비빔밥',
    price: 10000,
    image: require('../assets/foodImage/food_img_2.png'),
    selectImage: require('../assets/foodImage/food_s_img_2.png'),
    foodImage: require('../assets/foodImage/food_2.png'),
  },
  {
    id: 3,
    menu: '돌솥불고기\n비빔밥',
    price: 9500,
    image: require('../assets/foodImage/food_img_3.png'),
    selectImage: require('../assets/foodImage/food_s_img_3.png'),
    foodImage: require('../assets/foodImage/food_3.png'),
  },
  {
    id: 4,
    menu: '오징어덮밥',
    price: 9000,
    image: require('../assets/foodImage/food_img_4.png'),
    selectImage: require('../assets/foodImage/food_s_img_4.png'),
    foodImage: require('../assets/foodImage/food_4.png'),
  },
  {
    id: 5,
    menu: '된장찌개 정식',
    price: 10000,
    image: require('../assets/foodImage/food_img_5.png'),
    selectImage: require('../assets/foodImage/food_s_img_5.png'),
    foodImage: require('../assets/foodImage/food_5.png'),
  },
];
